# Generated by Django 2.1.7 on 2019-03-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('kids', models.ManyToManyField(to='front.Kid')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration', models.DurationField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='kid',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Parent'),
        ),
        migrations.AddField(
            model_name='kid',
            name='school_lvl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Level'),
        ),
    ]
